### ISSUE TITLE
Possible to get the full label?

### ISSUE THREAD

**Issue by mintreud** [brianleect/etherscan-labels#34]
Is it possible to config the app in such a way to retrieve the full label?

For example, many labels truncate with `...`, example:

- `0x495f947276749ce646f68ac8c248420045cb7b5e`
- `OpenSea Shar... (OPENST...)`

In this example, is it possible to retrieve `OpenSea Shared Storefront (OPENSTORE)` ?

**Comment by brianleect** [comment]
thanks for bringing this issue up @mintreud , I didn't notice the truncation happening in the scraped data previously.

I can try take a look at this issue but likely won't be resolved anytime soon as I'm busy.

Do feel free to attempt tackling this.  It should be doable by checking to see the layout of the page and identify the component that has the full label name. But atm its broken for etherscan due to possible anti-scraping mechanism or bugs.

**Comment by brianleect** [comment]
<span class="text-truncate" data-bs-toggle="tooltip">TZERO PREFER...</span>

Seems that full name is only visible when hovering over the name. Can't seem to find where the info is stored though

**Comment by brianleect** [comment]
![image](https://github.com/brianleect/etherscan-labels/assets/63389110/be4a82eb-bf7b-4737-9988-9c7344586459)

Document selector finds it hidden inside one of the properties.

**Comment by mintreud** [comment]
oh wow, thanks for the quick response @brianleect !

I see most of these are now fixed. Some null addresses still appear like this though: `Null Address: 0x000...000`

Only seems to affect null addresses - is that expected?
